# Generated by Django 3.0.2 on 2020-02-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contatc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatc',
            new_name='Contact',
        ),
    ]
